### ISSUE TITLE
`-s` flag not working on Windows?

### ISSUE THREAD

**Issue by leonardoraele** [w23/OpenSource#78]
I'm running it like this:

    OpenSource.exe hl1.cfg -s "Z:\SteamLibrary"

And I get this error:

```
D:\a\OpenSource\OpenSource\src\OpenSource.c:801: Default platform steam basedir = C:\Program Files (x86)/Steam/steamapps/common
D:\a\OpenSource\OpenSource\src\collection.c:293: Opening collection C:\Program Files (x86)/Steam/steamapps/common/Half-Life 2/hl1_hd/hl1_hd_pak_dir.vpk
D:\a\OpenSource\OpenSource\src\collection.c:293: Cannot open C:\Program Files (x86)/Steam/steamapps/common/Half-Life 2/hl1_hd/hl1_hd_pak_dir.vpk
```

My vpk files are actually at:

```
Z:\SteamLibrary\steamapps\common\Half-Life 2\hl1_hd\hl1_hd_pak_dir.vpk
```

It seems to me that the `-s` flag is being ignored.

<hr/>

System info:

> Windows 10 Pro
> 64-bit operating system, x64-based processor

Tested version:

> [v0.0.2c](https://github.com/w23/OpenSource/tree/v0.0.2c)
> [`29ff19f`](https://github.com/w23/OpenSource/commit/29ff19fd7119cc12439b01b0bcd8e4f09854b7d8)

**Comment by w23** [comment]
Thanks for the report!

I barely remember the details of this project, but I think the issue is that the order of arguments matters :sweat_smile:. I.e. `hl1.cfg` being before the `-s` flag means that it will be parsed w/o being aware of the custom steam dir.

Try placing the `-s` flag before `hl1.cfg`.

**Comment by leonardoraele** [comment]
Yes! That was the problem haha It worked now 🌮 🎉 Thank you!
